name: Component accessibility documentation
description: Submit the accessibility portion of your component 
title: '[Component name] component – accessibility '
labels: 'accessibility'
body:
  - type: markdown
    attributes:
      value: |
        Complete the following steps for Carbon to review the accessibility portion of the [component contribution process](https://carbondesignsystem.com/contributing/component/).

        1. Define component
        2. Document keyboard interactions
        3. Provide visual states
        4. Repeat steps 2 – 3 for each variant, if any
        5. Repeat step 3 for each child/subcomponent, if any

        _*variants are only when the interaction differs from default component, not when there are only visual differences_

        _*if the child/subcomponent is non-interactive, visual states may not be needed_
  - type: markdown
    attributes:
      value: '## 1. Define component'      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please conf     
